<?php
$z[0]=Array("channel"," <a href=\"[field:typeurl/]\" title=\"\">[field:typename/]</a>  | \r\n      ",90,212);
$z[0][4]['type']="top";
$z[0][4]['row']="10";
$z[1]=Array("global","",266,292);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",322,343);
$z[2][4]['name']="cfg_dz";
$z[3]=Array("global","",373,395);
$z[3][4]['name']="cfg_tel";
$z[4]=Array("global","",1056,1082);
$z[4][4]['name']="cfg_powerby";
$z[5]=Array("global","",1086,1110);
$z[5][4]['name']="cfg_beian";

?>